//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CompanyGroup.DataAccess.SqlServer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="customerId">No Metadata Documentation available.</param>
        /// <param name="dataAreaId">No Metadata Documentation available.</param>
        /// <param name="salesSource">No Metadata Documentation available.</param>
        /// <param name="salesStatus">No Metadata Documentation available.</param>
        /// <param name="salesType">No Metadata Documentation available.</param>
        /// <param name="onOrder">No Metadata Documentation available.</param>
        /// <param name="reserved">No Metadata Documentation available.</param>
        /// <param name="reservedOrdered">No Metadata Documentation available.</param>
        public ObjectResult<SalesList_Result> SalesList(global::System.String customerId, global::System.String dataAreaId, Nullable<global::System.Int32> salesSource, Nullable<global::System.Int32> salesStatus, Nullable<global::System.Int32> salesType, Nullable<global::System.Boolean> onOrder, Nullable<global::System.Boolean> reserved, Nullable<global::System.Boolean> reservedOrdered)
        {
            ObjectParameter customerIdParameter;
            if (customerId != null)
            {
                customerIdParameter = new ObjectParameter("CustomerId", customerId);
            }
            else
            {
                customerIdParameter = new ObjectParameter("CustomerId", typeof(global::System.String));
            }
    
            ObjectParameter dataAreaIdParameter;
            if (dataAreaId != null)
            {
                dataAreaIdParameter = new ObjectParameter("DataAreaId", dataAreaId);
            }
            else
            {
                dataAreaIdParameter = new ObjectParameter("DataAreaId", typeof(global::System.String));
            }
    
            ObjectParameter salesSourceParameter;
            if (salesSource.HasValue)
            {
                salesSourceParameter = new ObjectParameter("SalesSource", salesSource);
            }
            else
            {
                salesSourceParameter = new ObjectParameter("SalesSource", typeof(global::System.Int32));
            }
    
            ObjectParameter salesStatusParameter;
            if (salesStatus.HasValue)
            {
                salesStatusParameter = new ObjectParameter("SalesStatus", salesStatus);
            }
            else
            {
                salesStatusParameter = new ObjectParameter("SalesStatus", typeof(global::System.Int32));
            }
    
            ObjectParameter salesTypeParameter;
            if (salesType.HasValue)
            {
                salesTypeParameter = new ObjectParameter("SalesType", salesType);
            }
            else
            {
                salesTypeParameter = new ObjectParameter("SalesType", typeof(global::System.Int32));
            }
    
            ObjectParameter onOrderParameter;
            if (onOrder.HasValue)
            {
                onOrderParameter = new ObjectParameter("OnOrder", onOrder);
            }
            else
            {
                onOrderParameter = new ObjectParameter("OnOrder", typeof(global::System.Boolean));
            }
    
            ObjectParameter reservedParameter;
            if (reserved.HasValue)
            {
                reservedParameter = new ObjectParameter("Reserved", reserved);
            }
            else
            {
                reservedParameter = new ObjectParameter("Reserved", typeof(global::System.Boolean));
            }
    
            ObjectParameter reservedOrderedParameter;
            if (reservedOrdered.HasValue)
            {
                reservedOrderedParameter = new ObjectParameter("ReservedOrdered", reservedOrdered);
            }
            else
            {
                reservedOrderedParameter = new ObjectParameter("ReservedOrdered", typeof(global::System.Boolean));
            }
    
            return base.ExecuteFunction<SalesList_Result>("SalesList", customerIdParameter, dataAreaIdParameter, salesSourceParameter, salesStatusParameter, salesTypeParameter, onOrderParameter, reservedParameter, reservedOrderedParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="customerId">No Metadata Documentation available.</param>
        /// <param name="dataAreaId">No Metadata Documentation available.</param>
        public ObjectResult<CustomerLetterData_Result> CustomerLetterData(global::System.String customerId, global::System.String dataAreaId)
        {
            ObjectParameter customerIdParameter;
            if (customerId != null)
            {
                customerIdParameter = new ObjectParameter("CustomerId", customerId);
            }
            else
            {
                customerIdParameter = new ObjectParameter("CustomerId", typeof(global::System.String));
            }
    
            ObjectParameter dataAreaIdParameter;
            if (dataAreaId != null)
            {
                dataAreaIdParameter = new ObjectParameter("DataAreaId", dataAreaId);
            }
            else
            {
                dataAreaIdParameter = new ObjectParameter("DataAreaId", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<CustomerLetterData_Result>("CustomerLetterData", customerIdParameter, dataAreaIdParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DbModel", Name="CustomerLetterData_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class CustomerLetterData_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerLetterData_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="letterCity">Initial value of the LetterCity property.</param>
        /// <param name="letterCounty">Initial value of the LetterCounty property.</param>
        /// <param name="letterCountry">Initial value of the LetterCountry property.</param>
        /// <param name="letterStreet">Initial value of the LetterStreet property.</param>
        /// <param name="letterZipCode">Initial value of the LetterZipCode property.</param>
        public static CustomerLetterData_Result CreateCustomerLetterData_Result(global::System.Int32 id, global::System.String letterCity, global::System.String letterCounty, global::System.String letterCountry, global::System.String letterStreet, global::System.String letterZipCode)
        {
            CustomerLetterData_Result customerLetterData_Result = new CustomerLetterData_Result();
            customerLetterData_Result.Id = id;
            customerLetterData_Result.LetterCity = letterCity;
            customerLetterData_Result.LetterCounty = letterCounty;
            customerLetterData_Result.LetterCountry = letterCountry;
            customerLetterData_Result.LetterStreet = letterStreet;
            customerLetterData_Result.LetterZipCode = letterZipCode;
            return customerLetterData_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LetterCity
        {
            get
            {
                return _LetterCity;
            }
            set
            {
                OnLetterCityChanging(value);
                ReportPropertyChanging("LetterCity");
                _LetterCity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LetterCity");
                OnLetterCityChanged();
            }
        }
        private global::System.String _LetterCity;
        partial void OnLetterCityChanging(global::System.String value);
        partial void OnLetterCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LetterCounty
        {
            get
            {
                return _LetterCounty;
            }
            set
            {
                OnLetterCountyChanging(value);
                ReportPropertyChanging("LetterCounty");
                _LetterCounty = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LetterCounty");
                OnLetterCountyChanged();
            }
        }
        private global::System.String _LetterCounty;
        partial void OnLetterCountyChanging(global::System.String value);
        partial void OnLetterCountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LetterCountry
        {
            get
            {
                return _LetterCountry;
            }
            set
            {
                OnLetterCountryChanging(value);
                ReportPropertyChanging("LetterCountry");
                _LetterCountry = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LetterCountry");
                OnLetterCountryChanged();
            }
        }
        private global::System.String _LetterCountry;
        partial void OnLetterCountryChanging(global::System.String value);
        partial void OnLetterCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LetterStreet
        {
            get
            {
                return _LetterStreet;
            }
            set
            {
                OnLetterStreetChanging(value);
                ReportPropertyChanging("LetterStreet");
                _LetterStreet = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LetterStreet");
                OnLetterStreetChanged();
            }
        }
        private global::System.String _LetterStreet;
        partial void OnLetterStreetChanging(global::System.String value);
        partial void OnLetterStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LetterZipCode
        {
            get
            {
                return _LetterZipCode;
            }
            set
            {
                OnLetterZipCodeChanging(value);
                ReportPropertyChanging("LetterZipCode");
                _LetterZipCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LetterZipCode");
                OnLetterZipCodeChanged();
            }
        }
        private global::System.String _LetterZipCode;
        partial void OnLetterZipCodeChanging(global::System.String value);
        partial void OnLetterZipCodeChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DbModel", Name="SalesList_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SalesList_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SalesList_Result object.
        /// </summary>
        /// <param name="salesId">Initial value of the SalesId property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="inventLocationId">Initial value of the InventLocationId property.</param>
        /// <param name="payment">Initial value of the Payment property.</param>
        /// <param name="partialDischarge">Initial value of the PartialDischarge property.</param>
        /// <param name="autoDelete">Initial value of the AutoDelete property.</param>
        /// <param name="salesSource">Initial value of the SalesSource property.</param>
        /// <param name="headerSalesStatus">Initial value of the HeaderSalesStatus property.</param>
        /// <param name="shippingDateRequested">Initial value of the ShippingDateRequested property.</param>
        /// <param name="salesStatus">Initial value of the SalesStatus property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="statusIssue">Initial value of the StatusIssue property.</param>
        /// <param name="itemInventLocationId">Initial value of the ItemInventLocationId property.</param>
        /// <param name="currencyCode">Initial value of the CurrencyCode property.</param>
        public static SalesList_Result CreateSalesList_Result(global::System.String salesId, global::System.DateTime createdDate, global::System.String inventLocationId, global::System.String payment, global::System.Int32 partialDischarge, global::System.Int32 autoDelete, global::System.Int32 salesSource, global::System.Int32 headerSalesStatus, global::System.DateTime shippingDateRequested, global::System.Int32 salesStatus, global::System.String productId, global::System.String productName, global::System.Int32 statusIssue, global::System.String itemInventLocationId, global::System.String currencyCode)
        {
            SalesList_Result salesList_Result = new SalesList_Result();
            salesList_Result.SalesId = salesId;
            salesList_Result.CreatedDate = createdDate;
            salesList_Result.InventLocationId = inventLocationId;
            salesList_Result.Payment = payment;
            salesList_Result.PartialDischarge = partialDischarge;
            salesList_Result.AutoDelete = autoDelete;
            salesList_Result.SalesSource = salesSource;
            salesList_Result.HeaderSalesStatus = headerSalesStatus;
            salesList_Result.ShippingDateRequested = shippingDateRequested;
            salesList_Result.SalesStatus = salesStatus;
            salesList_Result.ProductId = productId;
            salesList_Result.ProductName = productName;
            salesList_Result.StatusIssue = statusIssue;
            salesList_Result.ItemInventLocationId = itemInventLocationId;
            salesList_Result.CurrencyCode = currencyCode;
            return salesList_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SalesId
        {
            get
            {
                return _SalesId;
            }
            set
            {
                OnSalesIdChanging(value);
                ReportPropertyChanging("SalesId");
                _SalesId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SalesId");
                OnSalesIdChanged();
            }
        }
        private global::System.String _SalesId;
        partial void OnSalesIdChanging(global::System.String value);
        partial void OnSalesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InventLocationId
        {
            get
            {
                return _InventLocationId;
            }
            set
            {
                OnInventLocationIdChanging(value);
                ReportPropertyChanging("InventLocationId");
                _InventLocationId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InventLocationId");
                OnInventLocationIdChanged();
            }
        }
        private global::System.String _InventLocationId;
        partial void OnInventLocationIdChanging(global::System.String value);
        partial void OnInventLocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Payment
        {
            get
            {
                return _Payment;
            }
            set
            {
                OnPaymentChanging(value);
                ReportPropertyChanging("Payment");
                _Payment = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Payment");
                OnPaymentChanged();
            }
        }
        private global::System.String _Payment;
        partial void OnPaymentChanging(global::System.String value);
        partial void OnPaymentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PartialDischarge
        {
            get
            {
                return _PartialDischarge;
            }
            set
            {
                OnPartialDischargeChanging(value);
                ReportPropertyChanging("PartialDischarge");
                _PartialDischarge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartialDischarge");
                OnPartialDischargeChanged();
            }
        }
        private global::System.Int32 _PartialDischarge;
        partial void OnPartialDischargeChanging(global::System.Int32 value);
        partial void OnPartialDischargeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AutoDelete
        {
            get
            {
                return _AutoDelete;
            }
            set
            {
                OnAutoDeleteChanging(value);
                ReportPropertyChanging("AutoDelete");
                _AutoDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoDelete");
                OnAutoDeleteChanged();
            }
        }
        private global::System.Int32 _AutoDelete;
        partial void OnAutoDeleteChanging(global::System.Int32 value);
        partial void OnAutoDeleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SalesSource
        {
            get
            {
                return _SalesSource;
            }
            set
            {
                OnSalesSourceChanging(value);
                ReportPropertyChanging("SalesSource");
                _SalesSource = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SalesSource");
                OnSalesSourceChanged();
            }
        }
        private global::System.Int32 _SalesSource;
        partial void OnSalesSourceChanging(global::System.Int32 value);
        partial void OnSalesSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeaderSalesStatus
        {
            get
            {
                return _HeaderSalesStatus;
            }
            set
            {
                OnHeaderSalesStatusChanging(value);
                ReportPropertyChanging("HeaderSalesStatus");
                _HeaderSalesStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeaderSalesStatus");
                OnHeaderSalesStatusChanged();
            }
        }
        private global::System.Int32 _HeaderSalesStatus;
        partial void OnHeaderSalesStatusChanging(global::System.Int32 value);
        partial void OnHeaderSalesStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ShippingDateRequested
        {
            get
            {
                return _ShippingDateRequested;
            }
            set
            {
                OnShippingDateRequestedChanging(value);
                ReportPropertyChanging("ShippingDateRequested");
                _ShippingDateRequested = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShippingDateRequested");
                OnShippingDateRequestedChanged();
            }
        }
        private global::System.DateTime _ShippingDateRequested;
        partial void OnShippingDateRequestedChanging(global::System.DateTime value);
        partial void OnShippingDateRequestedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LineNum
        {
            get
            {
                return _LineNum;
            }
            set
            {
                OnLineNumChanging(value);
                ReportPropertyChanging("LineNum");
                _LineNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LineNum");
                OnLineNumChanged();
            }
        }
        private Nullable<global::System.Int32> _LineNum;
        partial void OnLineNumChanging(Nullable<global::System.Int32> value);
        partial void OnLineNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SalesStatus
        {
            get
            {
                return _SalesStatus;
            }
            set
            {
                OnSalesStatusChanging(value);
                ReportPropertyChanging("SalesStatus");
                _SalesStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SalesStatus");
                OnSalesStatusChanged();
            }
        }
        private global::System.Int32 _SalesStatus;
        partial void OnSalesStatusChanging(global::System.Int32 value);
        partial void OnSalesStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.String _ProductId;
        partial void OnProductIdChanging(global::System.String value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SalesPrice
        {
            get
            {
                return _SalesPrice;
            }
            set
            {
                OnSalesPriceChanging(value);
                ReportPropertyChanging("SalesPrice");
                _SalesPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SalesPrice");
                OnSalesPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _SalesPrice;
        partial void OnSalesPriceChanging(Nullable<global::System.Int32> value);
        partial void OnSalesPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LineAmount
        {
            get
            {
                return _LineAmount;
            }
            set
            {
                OnLineAmountChanging(value);
                ReportPropertyChanging("LineAmount");
                _LineAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LineAmount");
                OnLineAmountChanged();
            }
        }
        private Nullable<global::System.Int32> _LineAmount;
        partial void OnLineAmountChanging(Nullable<global::System.Int32> value);
        partial void OnLineAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SalesDeliverNow
        {
            get
            {
                return _SalesDeliverNow;
            }
            set
            {
                OnSalesDeliverNowChanging(value);
                ReportPropertyChanging("SalesDeliverNow");
                _SalesDeliverNow = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SalesDeliverNow");
                OnSalesDeliverNowChanged();
            }
        }
        private Nullable<global::System.Int32> _SalesDeliverNow;
        partial void OnSalesDeliverNowChanging(Nullable<global::System.Int32> value);
        partial void OnSalesDeliverNowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RemainSalesPhysical
        {
            get
            {
                return _RemainSalesPhysical;
            }
            set
            {
                OnRemainSalesPhysicalChanging(value);
                ReportPropertyChanging("RemainSalesPhysical");
                _RemainSalesPhysical = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RemainSalesPhysical");
                OnRemainSalesPhysicalChanged();
            }
        }
        private Nullable<global::System.Int32> _RemainSalesPhysical;
        partial void OnRemainSalesPhysicalChanging(Nullable<global::System.Int32> value);
        partial void OnRemainSalesPhysicalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusIssue
        {
            get
            {
                return _StatusIssue;
            }
            set
            {
                OnStatusIssueChanging(value);
                ReportPropertyChanging("StatusIssue");
                _StatusIssue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusIssue");
                OnStatusIssueChanged();
            }
        }
        private global::System.Int32 _StatusIssue;
        partial void OnStatusIssueChanging(global::System.Int32 value);
        partial void OnStatusIssueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RecId
        {
            get
            {
                return _RecId;
            }
            set
            {
                OnRecIdChanging(value);
                ReportPropertyChanging("RecId");
                _RecId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecId");
                OnRecIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RecId;
        partial void OnRecIdChanging(Nullable<global::System.Int64> value);
        partial void OnRecIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemInventLocationId
        {
            get
            {
                return _ItemInventLocationId;
            }
            set
            {
                OnItemInventLocationIdChanging(value);
                ReportPropertyChanging("ItemInventLocationId");
                _ItemInventLocationId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemInventLocationId");
                OnItemInventLocationIdChanged();
            }
        }
        private global::System.String _ItemInventLocationId;
        partial void OnItemInventLocationIdChanging(global::System.String value);
        partial void OnItemInventLocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CurrencyCode
        {
            get
            {
                return _CurrencyCode;
            }
            set
            {
                OnCurrencyCodeChanging(value);
                ReportPropertyChanging("CurrencyCode");
                _CurrencyCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CurrencyCode");
                OnCurrencyCodeChanged();
            }
        }
        private global::System.String _CurrencyCode;
        partial void OnCurrencyCodeChanging(global::System.String value);
        partial void OnCurrencyCodeChanged();

        #endregion
    }

    #endregion
    
}
