//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyGroup.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyGroup.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot associate transient or null structure!.
        /// </summary>
        public static string exception_CannotAssociateTransientOrNullStructure {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category identifier can not be null, or empty!.
        /// </summary>
        public static string validation_CategoryIdCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CategoryIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name can not be null, or empty!.
        /// </summary>
        public static string validation_CategoryNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CategoryNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password log id cannot be null or empty!.
        /// </summary>
        public static string validation_ChangePasswordLogIdCannotBeNull {
            get {
                return ResourceManager.GetString("validation_ChangePasswordLogIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item identifier can not be null! .
        /// </summary>
        public static string validation_ItemIdCannotBeNull {
            get {
                return ResourceManager.GetString("validation_ItemIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer identifier can not be null, or empty!.
        /// </summary>
        public static string validation_ManufacturerIdCannotBeNull {
            get {
                return ResourceManager.GetString("validation_ManufacturerIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer name can not be null, or empty!.
        /// </summary>
        public static string validation_ManufacturerNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_ManufacturerNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product manager identifier can not be null, or empty!.
        /// </summary>
        public static string validation_ProductManagerIdCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("validation_ProductManagerIdCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product manager name can not be null, or empty!.
        /// </summary>
        public static string validation_ProductManagerNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("validation_ProductManagerNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile identifier can not be null!.
        /// </summary>
        public static string validation_ProfileIdCannotBeNull {
            get {
                return ResourceManager.GetString("validation_ProfileIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor identifier can not be null, or empty!.
        /// </summary>
        public static string validationVisitorIdCannotBeNull {
            get {
                return ResourceManager.GetString("validationVisitorIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change password mail has not been sent!.
        /// </summary>
        public static string verification_ChangePasswordMailSendFailed {
            get {
                return ResourceManager.GetString("verification_ChangePasswordMailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change password operation not allowed!.
        /// </summary>
        public static string verification_ChangePasswordNotAllowed {
            get {
                return ResourceManager.GetString("verification_ChangePasswordNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is alerady in use!.
        /// </summary>
        public static string verification_PasswordAleradyExists {
            get {
                return ResourceManager.GetString("verification_PasswordAleradyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The undo change password operation is successed!.
        /// </summary>
        public static string verification_UndoChangePassword {
            get {
                return ResourceManager.GetString("verification_UndoChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password are not found!.
        /// </summary>
        public static string verification_UserNamePasswordNotFound {
            get {
                return ResourceManager.GetString("verification_UserNamePasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name and password are all right..
        /// </summary>
        public static string verification_UserNamePasswordOK {
            get {
                return ResourceManager.GetString("verification_UserNamePasswordOK", resourceCulture);
            }
        }
    }
}
